"""add api_key_hash and backfill from plaintext api_key

Revision ID: a1f2c3d4e5f6
Revises: b3c33f993272
Create Date: 2026-09-20 16:10:00.000000

Step 1 of 2 in moving off plaintext API keys (see next migration for the
drop). Written by hand rather than autogenerated: the backfill needs
application logic (HMAC with a server-side pepper), which autogenerate
has no way to know about, and this migration is intentionally frozen -
it hashes with the exact same algorithm services/auth.hash_api_key used
at the time this was written, independent of whatever that function
looks like later.
"""

import hashlib
import hmac
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1f2c3d4e5f6"
down_revision: str | Sequence[str] | None = "b3c33f993272"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("customers", sa.Column("api_key_hash", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_customers_api_key_hash"), "customers", ["api_key_hash"], unique=True)

    # Backfill existing plaintext keys. Import here (not at module scope) so
    # this file stays self-contained and doesn't affect other migrations'
    # import time.
    from app.config import get_settings

    pepper = get_settings().api_key_pepper.encode()
    bind = op.get_bind()

    customers_table = sa.table(
        "customers",
        sa.column("customer_id", sa.String),
        sa.column("api_key", sa.String),
        sa.column("api_key_hash", sa.String),
    )

    rows = bind.execute(sa.select(customers_table.c.customer_id, customers_table.c.api_key))
    for customer_id, api_key in rows:
        digest = hmac.new(pepper, api_key.encode(), hashlib.sha256).hexdigest()
        bind.execute(
            customers_table.update()
            .where(customers_table.c.customer_id == customer_id)
            .values(api_key_hash=digest)
        )


def downgrade() -> None:
    op.drop_index(op.f("ix_customers_api_key_hash"), table_name="customers")
    op.drop_column("customers", "api_key_hash")
