"""baseline schema

Revision ID: b3c33f993272
Revises:
Create Date: 2026-09-20 16:01:39.906832

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3c33f993272"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_records",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("customer_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("policy_version", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=False),
        sa.Column("matched_rule", sa.String(length=500), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("escalation_id", sa.String(length=255), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("resolution", sa.String(length=50), nullable=True),
        sa.Column("resolution_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_result", sa.JSON(), nullable=True),
        sa.Column("execution_error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("record_id", "timestamp"),
    )
    op.create_index("idx_agent_timestamp", "audit_records", ["agent_id", "timestamp"], unique=False)
    op.create_index(
        "idx_customer_agent_timestamp",
        "audit_records",
        ["customer_id", "agent_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_customer_outcome", "audit_records", ["customer_id", "outcome"], unique=False
    )
    op.create_index(
        "idx_customer_timestamp", "audit_records", ["customer_id", "timestamp"], unique=False
    )
    op.create_index(
        "idx_customer_tool", "audit_records", ["customer_id", "tool_name"], unique=False
    )
    op.create_index(op.f("ix_audit_records_agent_id"), "audit_records", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_audit_records_customer_id"), "audit_records", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_escalation_id"), "audit_records", ["escalation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_records_outcome"), "audit_records", ["outcome"], unique=False)
    op.create_index(
        op.f("ix_audit_records_session_id"), "audit_records", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_timestamp"), "audit_records", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_tool_name"), "audit_records", ["tool_name"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("customer_id"),
    )
    op.create_index(op.f("ix_customers_api_key"), "customers", ["api_key"], unique=True)
    op.create_table(
        "escalations",
        sa.Column("escalation_id", sa.String(length=255), nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("resolution_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("escalation_id"),
    )
    op.create_index("idx_agent_status", "escalations", ["agent_id", "status"], unique=False)
    op.create_index("idx_customer_status", "escalations", ["customer_id", "status"], unique=False)
    op.create_index(op.f("ix_escalations_agent_id"), "escalations", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_escalations_customer_id"), "escalations", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_escalations_record_id"), "escalations", ["record_id"], unique=False)
    op.create_index(op.f("ix_escalations_status"), "escalations", ["status"], unique=False)
    op.create_table(
        "policies",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("policy_yaml", sa.Text(), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("policy_id"),
    )
    op.create_index("idx_customer_agent", "policies", ["customer_id", "agent_id"], unique=False)
    op.create_index(
        "idx_customer_agent_active",
        "policies",
        ["customer_id", "agent_id", "is_active"],
        unique=False,
    )
    op.create_index(op.f("ix_policies_agent_id"), "policies", ["agent_id"], unique=False)
    op.create_index(op.f("ix_policies_customer_id"), "policies", ["customer_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("customer_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("token_id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # audit_records is meant to be a TimescaleDB hypertable (see its model
    # docstring), but the previous setup (docker-entrypoint-initdb.d/init.sql
    # checking for the table's existence) ran before SQLAlchemy's
    # create_all() had ever created it, so the condition was always false
    # and conversion silently never happened. Do it here instead, right
    # after the table exists, so it actually takes effect. No-op on SQLite
    # (used by the test suite), which has no such extension.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
        op.execute(
            "SELECT create_hypertable('audit_records', 'timestamp', "
            "if_not_exists => TRUE, migrate_data => TRUE)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_policies_customer_id"), table_name="policies")
    op.drop_index(op.f("ix_policies_agent_id"), table_name="policies")
    op.drop_index("idx_customer_agent_active", table_name="policies")
    op.drop_index("idx_customer_agent", table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_escalations_status"), table_name="escalations")
    op.drop_index(op.f("ix_escalations_record_id"), table_name="escalations")
    op.drop_index(op.f("ix_escalations_customer_id"), table_name="escalations")
    op.drop_index(op.f("ix_escalations_agent_id"), table_name="escalations")
    op.drop_index("idx_customer_status", table_name="escalations")
    op.drop_index("idx_agent_status", table_name="escalations")
    op.drop_table("escalations")
    op.drop_index(op.f("ix_customers_api_key"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_audit_records_tool_name"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_timestamp"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_session_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_outcome"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_escalation_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_customer_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_agent_id"), table_name="audit_records")
    op.drop_index("idx_customer_tool", table_name="audit_records")
    op.drop_index("idx_customer_timestamp", table_name="audit_records")
    op.drop_index("idx_customer_outcome", table_name="audit_records")
    op.drop_index("idx_customer_agent_timestamp", table_name="audit_records")
    op.drop_index("idx_agent_timestamp", table_name="audit_records")
    op.drop_table("audit_records")
    # ### end Alembic commands ###
