"""drop plaintext api_key

Revision ID: ccbac028b217
Revises: a1f2c3d4e5f6
Create Date: 2026-09-20 16:08:45.806258

Step 2 of 2 in moving off plaintext API keys. Hashing is one-way, so
downgrade() cannot restore the original plaintext values it deletes here -
it only restores the column shape (populated with NULLs) for a schema-only
rollback.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccbac028b217"
down_revision: str | Sequence[str] | None = "a1f2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers", "api_key_hash", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.drop_index(op.f("ix_customers_api_key"), table_name="customers")
    op.drop_column("customers", "api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Nullable, not NOT NULL like the original column: the plaintext values
    # are gone for good, so existing rows get NULL rather than a constraint
    # violation.
    op.add_column(
        "customers",
        sa.Column("api_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.create_index(op.f("ix_customers_api_key"), "customers", ["api_key"], unique=True)
    op.alter_column("customers", "api_key_hash", existing_type=sa.VARCHAR(length=64), nullable=True)
