-- Initialize TimescaleDB extension.
--
-- This runs once, automatically, on first Postgres startup, before any
-- tables exist - which is why hypertable conversion isn't attempted here.
-- It used to be (via a conditional DO block checking for audit_records),
-- but that check always evaluated false at this point in the container
-- lifecycle, so it silently never ran. Schema creation and the
-- audit_records -> hypertable conversion are both handled by the Alembic
-- baseline migration instead (alembic/versions/*_baseline_schema.py),
-- applied via `alembic upgrade head` after this container is up.
CREATE EXTENSION IF NOT EXISTS timescaledb;
